# Generated by Django 3.2.16 on 2026-03-22 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='Имя')),
            ],
        ),
        migrations.AddField(
            model_name='birthday',
            name='city',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='birthday.cities'),
            preserve_default=False,
        ),
    ]
