# Generated by Django 3.2.16 on 2026-03-22 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0002_auto_20260322_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthday',
            name='city',
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
